### ISSUE TITLE
User Story: User Access to site text

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/my-first-project#5]
In order to **Change the content** as a **Administrator**, I can **Access the site content by logging in**

# Acceptance Criteria:
- Acceptance Criteria 1: Create a administrator log in.
- Acceptance Criteria 2: Create a save feature for administrator
- Acceptance Criteria 3: Add added verification method for administrator

# Tasks
- [] Create a administrator log in.
- [] Create a tic box to save admin credentials
- [] Create an additional google verification method.

**Comment by Julius-88** [comment]
completed
