### ISSUE TITLE
User Story: Administrator

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/my-first-project#6]
In order to **change the content** as a **administrator**, I can **have the option next to each content to edit**

# Acceptance Criteria:
- Acceptance Criteria 1: Allow the administrator to edit the content
- Acceptance Criteria 2: Allow the administrator to preview the content
- Acceptance Criteria 3: Allow the administrator to save the content

# Tasks
- [] Create a edit function next to each text content
- [] Create a preview module to add into each edit function
- [] Create a save button
