### ISSUE TITLE
User Story: Administrator poll change

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/my-first-project#7]
In order to **be able to get different feedback** as a **adminitrator**, I can **access the poll**

# Acceptance Criteria:
- Acceptance Criteria 1: Allow the administrator to gain access to the poll
- Acceptance Criteria 2: Allow the administrator to edit the poll
- Acceptance Criteria 3: Allow the administrator to save the poll

# Tasks
- [ ] Create a edit function for the poll, for admin
- [ ] Create a preview function for the poll, for admin
- [ ] Create a save function for the poll, for admin
